version: '3.8'

services:
  shopping-app:
    image: node:18-slim
    container_name: shopping-app
    ports:
      - "8100:8100"
      - "35729:35729"  # Livereload port (opzionale, ma consigliato)
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - CHOKIDAR_USEPOLLING=true  # Forza il watcher a polling (funziona bene su Docker)
    command: bash -c "npm install -g @ionic/cli && npm install && ionic serve --external --no-open --lab"